baseURL: https://nsddd.top
title: cubxxw is blog
theme: PaperMod

# Config WIKI
# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true
googleAnalytics: G-FSWQC2Y01E
pygmentsUseClasses: true
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: ExampleSite
  description: ExampleSite description
  keywords:
    - Blog
    - CloudNative
    - cubxxw
  author: Me
  images:
    - <link or path of image for opengraph, twitter-cards>
  DateFormat: January 2, 2006
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  
  showtoc: true
  tocopen: true
  assets:
    favicon: ./favicon.ico
    favicon16x16: ./favicon-16x16.png
    favicon32x32: ./favicon-32x32.png
    apple_touch_icon: ./apple-touch-icon.png
    # safari_pinned_tab: <link / abs url>
    customCSS: ["css/custom.css"]
  label:
    text: Home
    icon: ./assets/cubxxw-image.jpg
    iconHeight: 35
  homeInfoParams:
    Title: Hi there ğŸ‘‹
    Content: My name is Xinwei(bear) Xiong. My loyalty is to adventure ğŸ¤–
  socialIcons:
    - name: github
      url: https://github.com/cubxxw
    - name: rss
      url: https://nsddd.top/index.xml
    - name: twitter
      url: https://twitter.com/xxw3293172751
    - name: stackoverflow
      url: https://stackoverflow.com/users/17393425/xinwei-xiong
    - name: zhihu
      url: https://www.zhihu.com/people/3293172751
    - name: linkedin
      url: https://www.linkedin.com/in/cubxxw
    - name: facebook
      url: https://www.facebook.com/profile.php?id=100034435372354
    - name: wechat
      url: /wechat.jpg
    - name: bilibili
      url: https://space.bilibili.com/1233089591
    - name: youtube
      url: https://www.youtube.com/channel/UCd3qbRbMwYlh5uKneo_2m_w
    - name: liberapay
      url: https://liberapay.com/xiongxinwei/donate
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/cubxxw
    - name: email
      url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&to=3293172751nss@gmail.com
    - name: weibo
      url: https://weibo.com/u/6248930985
    - name: jike
      url: https://web.okjike.com/u/56390e30-3288-4d20-a488-9f80161bbbf4
    - name: xhs
      url: https://www.xiaohongshu.com/user/profile/62a33af9000000001b025dd3
    - name: discord
      url: https://discordapp.com/users/1028126805300875295
  ShareButtons: ["linkedin", "twitter","bilibili","zhihu","email","facebook", "reddit", "telegram", "whatsapp", "ycombinator", "webo", "xiaohongshu"] # To customize which share buttons to be enabled on page
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    # https://www.fusejs.io/api/options.html#ignorefieldnorm
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
  sidebar:
    widgets:
      - type: "custom"
        title: "AIé¡¹ç›®å¯¼èˆª"
        template: "sidebar-ai-projects"

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

# languageCode: en-us
DefaultContentLanguage: en
# å¯ç”¨å¤šè¯­è¨€æ¨¡å¼
defaultContentLanguageInSubdir: false
# ç¦ç”¨è¯­è¨€å‰ç¼€ç§»é™¤ï¼ˆç¡®ä¿URLç»“æ„æ­£ç¡®ï¼‰
disableLanguages: []

languages:
  en:
    disabled: false
    languageCode: "en-us"
    languageDirection: "ltr"
    title: "Xinwei Xiong(cubxxw)'s English blog"
    contentDir: "content/en"
    languageName: English
    weight: 1
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸About me
          url: /about/
          pageRef: /about
          weight: 10
        - identifier: posts
          name: ğŸ“Posts
          url: /posts/
          pageRef: /posts
          weight: 15
        - identifier: travel
          name: ğŸŒTravel
          url: /travel/
          pageRef: /travel
          weight: 20
        - identifier: categories
          name: ğŸ—‚ï¸Categories
          url: categories/
          pageRef: /categories
          weight: 30
        - identifier: tags
          name: ğŸ·ï¸Tags
          url: tags/
          pageRef: /tags
          weight: 40
        - identifier:
          name: ğŸ”Search
          url: search/
          pageRef: /search
          weight: 50
        - identifier: 
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 60
        - identifier: diary
          name: ğŸ“”Diary
          url: https://diary.nsddd.top/flomo-enhanced
          weight: 70
    params:
      profileMode:
        # Enabled or not
        enabled: true
        title: Hi there ğŸ‘‹
        subtitle: |
          My name is Xinwei(bear) Xiong ğŸ¤–. My loyalty is to adventure â˜€ï¸,
          I'm a big open source fan â“‚ï¸. I have a big dream and will realize it next year.
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        # imageTitle: My name is bear
        buttons:
          - name: Posts
            url: posts
          - name: AI Projects
            url: categories/ai-open-source
          - name: archives
            url: archives
          - name: Tags
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/en"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link

  zh:
    disabled: false
    languageCode: "zh-cn"
    languageDirection: "ltr" # Left to Right for Chinese as well
    title: "ç†Šé‘«ä¼Ÿï¼ˆcubxxwï¼‰çš„ç®€ä½“ä¸­æ–‡åšå®¢ ğŸ‡¨ğŸ‡³"
    languageName: ç®€ä½“ä¸­æ–‡
    contentDir: "content/zh"
    weight: 2
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸å…³äºæˆ‘
          url: /about/
          pageRef: /about
          weight: 10
        - identifier: posts
          name: ğŸ“æ–‡ç« 
          url: /posts/
          pageRef: /posts
          weight: 15
        - identifier: travel
          name: ğŸŒæ—…è¡Œè¶³è¿¹
          url: /travel/
          pageRef: /travel
          weight: 20
        - identifier: categories
          name: ğŸ—‚ï¸åˆ†ç±»
          url: /categories/
          pageRef: /categories
          weight: 30
        - identifier: tags
          name: ğŸ·ï¸æ ‡ç­¾
          url: /tags/
          pageRef: /tags
          weight: 40
        - identifier: search
          name: ğŸ”æœç´¢
          url: /search/
          pageRef: /search
          weight: 50
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 60
        - identifier: diary
          name: ğŸ“”æ—¥è®°
          url: https://diary.nsddd.top/flomo-original
          weight: 70
    params:
      profileMode:
        # å¯ç”¨æˆ–ç¦ç”¨
        enabled: true
        title: ä½ å¥½ ğŸ‘‹
        subtitle: |
          æˆ‘å« Xinwei(bear) Xiong ğŸ¤–ã€‚æˆ‘çš„å¿ è¯šæ˜¯å¯¹å†’é™©çš„å¿ è¯šâ˜€ï¸ã€‚
          æˆ‘æ˜¯ä¸€ä¸ªå¼€æºçš„æåº¦çˆ±å¥½è€…â“‚ï¸ã€‚æˆ‘æœ‰ä¸€ä¸ªå¤§æ¢¦æƒ³ï¼Œå¹¶ä¼šåœ¨æ˜å¹´å®ç°å®ƒã€‚
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: æ–‡ç« 
            url: posts
          - name: AIå¼€æºé¡¹ç›®
            url: categories/ai-open-source
          - name: å½’æ¡£
            url: archives
          - name: æ ‡ç­¾
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/zh"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link'

  zh-tw:
    disabled: false
    languageCode: "zh-tw"
    languageDirection: "ltr"
    title: "ç†Šé‘«ä¼Ÿï¼ˆcubxxwï¼‰çš„ç¹ä½“ä¸­æ–‡åšå®¢"
    languageName: ç¹é«”ä¸­æ–‡
    contentDir: "content/zh-tw"
    weight: 5
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸é—œæ–¼æˆ‘
          url: /about/
          pageRef: /about
          weight: 10
        - identifier: posts
          name: ğŸ“æ–‡ç« 
          url: /posts/
          pageRef: /posts
          weight: 15
        - identifier: categories
          name: ğŸ—‚ï¸åˆ†é¡
          url: categories/
          pageRef: /categories
          weight: 30
        - identifier: tags
          name: ğŸ·ï¸æ¨™ç±¤
          url: tags/
          pageRef: /tags
          weight: 40
        - identifier: search
          name: ğŸ”æœç´¢
          url: search/
          pageRef: /search
          weight: 50
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 60
    params:
      profileMode:
        # å•Ÿç”¨æˆ–ç¦ç”¨
        enabled: true
        title: ä½ å¥½ ğŸ‘‹
        subtitle: |
          æˆ‘å« Xinwei(bear) Xiong ğŸ¤–ã€‚æˆ‘çš„å¿ èª æ˜¯å°å†’éšªçš„å¿ èª â˜€ï¸ã€‚
          æˆ‘æ˜¯ä¸€å€‹é–‹æºçš„æ¥µåº¦æ„›å¥½è€…â“‚ï¸ã€‚æˆ‘æœ‰ä¸€å€‹å¤§å¤¢æƒ³ï¼Œä¸¦æœƒåœ¨æ˜å¹´å¯¦ç¾å®ƒã€‚
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: æ–‡ç« 
            url: posts
          - name: AIé–‹æºé …ç›®
            url: categories/ai-open-source
          - name: æ­¸æª”
            url: archives
          - name: æ¨™ç±¤
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/zh-tw"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link
