baseURL: https://nsddd.top
title: cubxxw is blog
theme: PaperMod

# Config WIKI
# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
pygmentsUseClasses: true
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: ExampleSite
  description: ExampleSite description
  keywords:
    - Blog
    - CloudNative
    - cubxxw
  author: Me
  images:
    - <link or path of image for opengraph, twitter-cards>
  DateFormat: January 2, 2006
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowFullTextinRSS: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  
  showtoc: true
  tocopen: true
  assets:
    favicon: ./favicon.ico
    favicon16x16: ./favicon-16x16.png
    favicon32x32: ./favicon-32x32.png
    apple_touch_icon: ./apple-touch-icon.png
    # safari_pinned_tab: <link / abs url>
  label:
    text: Home
    icon: http://sm.nsddd.top/sm202309161719007.png
    iconHeight: 35
  homeInfoParams:
    Title: Hi there ğŸ‘‹
    Content: My name is Xinwei(bear) Xiong. My loyalty is to adventure ğŸ¤–
  socialIcons:
    - name: github
      url: https://github.com/cubxxw
    - name: rss
      url: https://nsddd.top/index.xml
    - name: twitter
      url: https://twitter.com/xxw3293172751
    - name: stackoverflow
      url: https://stackoverflow.com/users/17393425/xinwei-xiong
    - name: zhihu
      url: https://www.zhihu.com/people/3293172751
    - name: linkedin
      url: https://www.linkedin.com/in/cubxxw
    - name: keybase
      url: https://calendly.com/cubxxw
    - name: facebook
      url: https://www.facebook.com/profile.php?id=100034435372354
    - name: wechat
      url: https://sm.nsddd.top/sm0d220ad72063197b9875379403f6c88.jpg
    - name: bilibili
      url: https://space.bilibili.com/1233089591
    - name: youtube
      url: https://https//www.youtube.com/channel/UCd3qbRbMwYlh5uKneo_2m_w
    - name: liberapay
      url: https://liberapay.com/xiongxinwei/donate
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/cubxxw
    - name: email
      url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&to=3293172751nss@gmail.com
    - name: weibo
      url: https://weibo.com/u/6248930985
  ShareButtons: ["linkedin", "twitter","bilibili","zhihu","email","facebook", "reddit", "telegram", "whatsapp", "ycombinator", "webo", "xiaohongshu"] # To customize which share buttons to be enabled on page
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    # https://www.fusejs.io/api/options.html#ignorefieldnorm
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

markup:
  highlight:
    noClasses: false
outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

# languageCode: en-us
DefaultContentLanguage: en
languages:
  en:
    disabled: false
    languageCode: "en-us"
    languageDirection: "English Blog"
    title: "Xinwei Xiong(cubxxw)'s English blog"
    contentDir: "content/en"
    languageName: English
    weight: 1
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸About me
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸Categories
          url: categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸Tags
          url: tags/
          pageRef: /tags
          weight: 30
        - identifier:
          name: ğŸ”Search
          url: search/
          pageRef: /search
          weight: 40
        - identifier: 
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # Enabled or not
        enabled: true
        title: Hi there ğŸ‘‹
        subtitle: |
          My name is Xinwei(bear) Xiong ğŸ¤–. My loyalty is to adventure â˜€ï¸,
          I'm a big open source fan â“‚ï¸. I have a big dream and will realize it next year.
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        # imageTitle: My name is bear
        buttons:
          - name: Posts
            url: posts
          - name: archives
            url: archives
          - name: Tags
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/en"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link

  fr:
    disabled: false
    languageCode: "fr-fr"
    languageDirection: "ltr" # Left to Right for French as well
    title: "Blog en franÃ§ais de Xinwei Xiong (cubxxw) ğŸ‡«ğŸ‡·"
    contentDir: "content/fr"
    languageName: FranÃ§ais
    weight: 4
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸Ã€ propos de moi
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸CatÃ©gories
          url: categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸Ã‰tiquettes
          url: tags/
          pageRef: /tags
          weight: 30
        - identifier: search
          name: ğŸ”Recherche
          url: search/
          pageRef: /search
          weight: 40
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # ActivÃ© ou non
        enabled: true
        title: Salut ğŸ‘‹
        subtitle: |
          Je m'appelle Xinwei(bear) Xiong ğŸ¤–. Ma loyautÃ© est Ã  l'aventure â˜€ï¸.
          Je suis un grand fan de l'open source â“‚ï¸. J'ai un grand rÃªve et je le rÃ©aliserai l'annÃ©e prochaine.
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: Articles
            url: posts
          - name: Archives
            url: archives
          - name: Ã‰tiquettes
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/fr"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link

  es:
    disabled: false
    languageCode: "es-es"
    languageDirection: "ltr" # Left to Right for Spanish as well
    title: "Blog en espaÃ±ol de Xinwei Xiong (cubxxw) ğŸ‡ªğŸ‡¸"
    contentDir: "content/es"
    languageName: EspaÃ±ol
    weight: 3
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸Acerca de mÃ­
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸CategorÃ­as
          url: categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸Etiquetas
          url: tags/
          pageRef: /tags
          weight: 30
        - identifier: search
          name: ğŸ”Buscar
          url: search/
          pageRef: /search
          weight: 40
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # Habilitado o no
        enabled: true
        title: Hola ğŸ‘‹
        subtitle: |
          Mi nombre es Xinwei(bear) Xiong ğŸ¤–. Mi lealtad es a la aventura â˜€ï¸.
          Soy un gran fanÃ¡tico del cÃ³digo abierto â“‚ï¸. Tengo un gran sueÃ±o y lo harÃ© realidad el prÃ³ximo aÃ±o.
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: Publicaciones
            url: posts
          - name: Archivos
            url: archives
          - name: Etiquetas
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/es"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link

  de:
    disabled: false
    languageCode: "de-DE"
    languageDirection: "ltr"
    title: "Deutscher Blog von Xinwei Xiong (cubxxw) ğŸ‡©ğŸ‡ª"
    contentDir: "content/de"
    languageName: "Deutsch"
    weight: 6
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸Ãœber mich
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸Kategorien
          url: categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸Tags
          url: tags/
          pageRef: /tags
          weight: 30
        - identifier: search
          name: ğŸ”Suche
          url: search/
          pageRef: /search
          weight: 40
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # Habilitado o no
        enabled: true
        title: Hallo ğŸ‘‹
        subtitle: |
          Mein Name ist Xinwei (BÃ¤r) Xiong ğŸ¤–. Meine LoyalitÃ¤t gilt dem Abenteuer â˜€ï¸.
          Ich bin ein groÃŸer Fan von Open Source â“‚ï¸. Ich habe einen groÃŸen Traum und werde ihn im nÃ¤chsten Jahr wahr machen.
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: BeitrÃ¤ge
            url: posts
          - name: Archive
            url: archives
          - name: Tags
            url: tags
      editPost:
        URL: "https://github.com/cubxxw/blog/edit/main/content/de"
        Text: "Ã„nderungen vorschlagen" # edit text
        appendFilePath: true # to append file path to Edit link

  zh:
    disabled: false
    languageCode: "zh-cn"
    languageDirection: "ltr" # Left to Right for Chinese as well
    title: "ç†Šé‘«ä¼Ÿï¼ˆcubxxwï¼‰çš„ç®€ä½“ä¸­æ–‡åšå®¢ ğŸ‡¨ğŸ‡³"
    languageName: ç®€ä½“ä¸­æ–‡
    contentDir: "content/zh"
    weight: 2
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸å…³äºæˆ‘
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸åˆ†ç±»
          url: /categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸æ ‡ç­¾
          url: /tags/
          pageRef: /tags
          weight: 30
        - identifier: search
          name: ğŸ”æœç´¢
          url: /search/
          pageRef: /search
          weight: 40
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # å¯ç”¨æˆ–ç¦ç”¨
        enabled: true
        title: ä½ å¥½ ğŸ‘‹
        subtitle: |
          æˆ‘å« Xinwei(bear) Xiong ğŸ¤–ã€‚æˆ‘çš„å¿ è¯šæ˜¯å¯¹å†’é™©çš„å¿ è¯šâ˜€ï¸ã€‚
          æˆ‘æ˜¯ä¸€ä¸ªå¼€æºçš„æåº¦çˆ±å¥½è€…â“‚ï¸ã€‚æˆ‘æœ‰ä¸€ä¸ªå¤§æ¢¦æƒ³ï¼Œå¹¶ä¼šåœ¨æ˜å¹´å®ç°å®ƒã€‚
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: æ–‡ç« 
            url: posts
          - name: å½’æ¡£
            url: archives
          - name: æ ‡ç­¾
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/zh"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link'

  zh-tw:
    disabled: false
    languageCode: "zh-tw"
    languageDirection: "ltr"
    title: "ç†Šé‘«ä¼Ÿï¼ˆcubxxwï¼‰çš„ç¹ä½“ä¸­æ–‡åšå®¢"
    languageName: ç¹é«”ä¸­æ–‡
    contentDir: "content/zh-tw"
    weight: 5
    menu:
      main:
        - identifier: lint
          name: ğŸ¤¸é—œæ–¼æˆ‘
          url: https://nsddd.top
          pageRef: /lint
          weight: 10
        - identifier: categories
          name: ğŸ—‚ï¸åˆ†é¡
          url: categories/
          pageRef: /categories
          weight: 20
        - identifier: tags
          name: ğŸ·ï¸æ¨™ç±¤
          url: tags/
          pageRef: /tags
          weight: 30
        - identifier: search
          name: ğŸ”æœç´¢
          url: search/
          pageRef: /search
          weight: 40
        - identifier: github
          name: â“‚ï¸Github
          url: https://github.com/cubxxw/blog
          weight: 50
    params:
      profileMode:
        # å•Ÿç”¨æˆ–ç¦ç”¨
        enabled: true
        title: ä½ å¥½ ğŸ‘‹
        subtitle: |
          æˆ‘å« Xinwei(bear) Xiong ğŸ¤–ã€‚æˆ‘çš„å¿ èª æ˜¯å°å†’éšªçš„å¿ èª â˜€ï¸ã€‚
          æˆ‘æ˜¯ä¸€å€‹é–‹æºçš„æ¥µåº¦æ„›å¥½è€…â“‚ï¸ã€‚æˆ‘æœ‰ä¸€å€‹å¤§å¤¢æƒ³ï¼Œä¸¦æœƒåœ¨æ˜å¹´å¯¦ç¾å®ƒã€‚
        imageUrl: ../assets/cubxxw-image.jpg
        imageWidth: 120
        imageHeight: 120
        buttons:
          - name: æ–‡ç« 
            url: posts
          - name: æ­¸æª”
            url: archives
          - name: æ¨™ç±¤
            url: tags
      editPost:
          URL: "https://github.com/cubxxw/blog/edit/main/content/zh-tw"
          Text: "Suggest Changes" # edit text
          appendFilePath: true # to append file path to Edit link