name: Github Pull Request
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
      - name: Setup Go
        uses: actions/setup-go@v6
      - name: Run go modules tidy
        run: |
          sudo apt-get install jq
        continue-on-error: true

      - name: Run make build
        run: |
          sudo make build
        continue-on-error: true

      - name: Run make module-init
        run: |
          sudo make module-init
          sudo make module-update
          sudo make module-check
        continue-on-error: true

      - name: Copy Readme file to pubilc
        run: |
          cp README.md ./static/
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: "cicd: bump League Patch"
          author: kubbot <3293172751ysy@gmail.com>
          committer: kubbot <3293172751ysy@gmail.com>
        #   signoff: false
        #   draft: false
          branch: "asf-auto-updates"
          assignees: cubxxw
          reviewers: cubxxw
          title: "[Auto PR ðŸ¤–] Bump League Patch auto PR"
          body: |
            I am a PR generated by robot automation.

            Review criteria:

            - [ ] Disenchanter can connect and issue actions

            Github Actions Status:

            [![Github Pull Request](https://github.com/cubxxw/blog/actions/workflows/pull-request.yml/badge.svg)](https://github.com/openimsdk/open-im-server/actions/workflows/pull-request.yml)
            
            This is an automated PR. 
            <sub>[workflow](https://github.com/cubxxw/blog/blob/main/.github/workflows/pull-request.yml).</sub>
          labels: |
            kind/documentation
            enhancement
            report